/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Root
		 * @description Root endpoint that returns a welcome message.
		 */
		get: operations["root__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint for liveness/readiness probes.
		 */
		get: operations["health_check_health_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health/detailed": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Detailed Health Check
		 * @description Comprehensive health status with component details.
		 */
		get: operations["detailed_health_check_health_detailed_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Auth:Cookie.Login */
		post: operations["auth_cookie_login_api_v1_auth_login_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Auth:Cookie.Logout */
		post: operations["auth_cookie_logout_api_v1_auth_logout_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Me */
		get: operations["get_me_api_v1_auth_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register:Register */
		post: operations["register_register_api_v1_auth_register_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/forgot-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reset:Forgot Password */
		post: operations["reset_forgot_password_api_v1_auth_forgot_password_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/reset-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reset:Reset Password */
		post: operations["reset_reset_password_api_v1_auth_reset_password_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/request-verify-token": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify:Request-Token */
		post: operations["verify_request_token_api_v1_auth_request_verify_token_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/verify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify:Verify */
		post: operations["verify_verify_api_v1_auth_verify_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/add": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add
		 * @description Add data to a dataset for processing and knowledge graph construction.
		 *
		 *     This endpoint accepts various types of data (files, URLs, GitHub repositories)
		 *     and adds them to a specified dataset for processing. The data is ingested,
		 *     analyzed, and integrated into the knowledge graph.
		 *
		 *     ## Request Parameters
		 *     - **data** (List[UploadFile]): List of files to upload. Can also include:
		 *       - HTTP URLs (if ALLOW_HTTP_REQUESTS is enabled)
		 *       - GitHub repository URLs (will be cloned and processed)
		 *       - Regular file uploads
		 *     - **datasetName** (Optional[str]): Name of the dataset to add data to
		 *     - **datasetId** (Optional[UUID]): UUID of an already existing dataset
		 *     - **node_set** Optional[list[str]]: List of node identifiers for graph organization and access control.
		 *              Used for grouping related data points in the knowledge graph.
		 *
		 *     Either datasetName or datasetId must be provided.
		 *
		 *     ## Response
		 *     Returns information about the add operation containing:
		 *     - Status of the operation
		 *     - Details about the processed data
		 *     - Any relevant metadata from the ingestion process
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Neither datasetId nor datasetName provided
		 *     - **409 Conflict**: Error during add operation
		 *     - **403 Forbidden**: User doesn't have permission to add to dataset
		 *
		 *     ## Notes
		 *     - To add data to datasets not owned by the user, use dataset_id (when ENABLE_BACKEND_ACCESS_CONTROL is set to True)
		 *     - datasetId value can only be the UUID of an already existing dataset
		 */
		post: operations["add_api_v1_add_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cognify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Cognify
		 * @description Transform datasets into structured knowledge graphs through cognitive processing.
		 *
		 *     This endpoint is the core of Cognee's intelligence layer, responsible for converting
		 *     raw text, documents, and data added through the add endpoint into semantic knowledge graphs.
		 *     It performs deep analysis to extract entities, relationships, and insights from ingested content.
		 *
		 *     ## Processing Pipeline
		 *     1. Document classification and permission validation
		 *     2. Text chunking and semantic segmentation
		 *     3. Entity extraction using LLM-powered analysis
		 *     4. Relationship detection and graph construction
		 *     5. Vector embeddings generation for semantic search
		 *     6. Content summarization and indexing
		 *
		 *     ## Request Parameters
		 *     - **datasets** (Optional[List[str]]): List of dataset names to process. Dataset names are resolved to datasets owned by the authenticated user.
		 *     - **dataset_ids** (Optional[List[UUID]]): List of existing dataset UUIDs to process. UUIDs allow processing of datasets not owned by the user (if permitted).
		 *     - **run_in_background** (Optional[bool]): Whether to execute processing asynchronously. Defaults to False (blocking).
		 *     - **custom_prompt** (Optional[str]): Custom prompt for entity extraction and graph generation. If provided, this prompt will be used instead of the default prompts for knowledge graph extraction.
		 *
		 *     ## Response
		 *     - **Blocking execution**: Complete pipeline run information with entity counts, processing duration, and success/failure status
		 *     - **Background execution**: Pipeline run metadata including pipeline_run_id for status monitoring via WebSocket subscription
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: When neither datasets nor dataset_ids are provided, or when specified datasets don't exist
		 *     - **409 Conflict**: When processing fails due to system errors, missing LLM API keys, database connection failures, or corrupted content
		 *
		 *     ## Example Request
		 *     ```json
		 *     {
		 *         "datasets": ["research_papers", "documentation"],
		 *         "run_in_background": false,
		 *         "custom_prompt": "Extract entities focusing on technical concepts and their relationships. Identify key technologies, methodologies, and their interconnections."
		 *     }
		 *     ```
		 *
		 *     ## Notes
		 *     To cognify data in datasets not owned by the user and for which the current user has write permission,
		 *     the dataset_id must be used (when ENABLE_BACKEND_ACCESS_CONTROL is set to True).
		 *
		 *     ## Next Steps
		 *     After successful processing, use the search endpoints to query the generated knowledge graph for insights, relationships, and semantic search.
		 */
		post: operations["cognify_api_v1_cognify_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/memify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Memify
		 * @description Enrichment pipeline in Cognee, can work with already built graphs. If no data is provided existing knowledge graph will be used as data,
		 *     custom data can also be provided instead which can be processed with provided extraction and enrichment tasks.
		 *
		 *     Provided tasks and data will be arranged to run the Cognee pipeline and execute graph enrichment/creation.
		 *
		 *     ## Request Parameters
		 *     - **extractionTasks** Optional[List[str]]: List of available Cognee Tasks to execute for graph/data extraction.
		 *     - **enrichmentTasks** Optional[List[str]]: List of available Cognee Tasks to handle enrichment of provided graph/data from extraction tasks.
		 *     - **data** Optional[List[str]]: The data to ingest. Can be any text data when custom extraction and enrichment tasks are used.
		 *           Data provided here will be forwarded to the first extraction task in the pipeline as input.
		 *           If no data is provided the whole graph (or subgraph if node_name/node_type is specified) will be forwarded
		 *     - **dataset_name** (Optional[str]): Name of the datasets to memify
		 *     - **dataset_id** (Optional[UUID]): List of UUIDs of an already existing dataset
		 *     - **node_name** (Optional[List[str]]):  Filter graph to specific named entities (for targeted search). Used when no data is provided.
		 *     - **run_in_background** (Optional[bool]): Whether to execute processing asynchronously. Defaults to False (blocking).
		 *
		 *     Either datasetName or datasetId must be provided.
		 *
		 *     ## Response
		 *     Returns information about the add operation containing:
		 *     - Status of the operation
		 *     - Details about the processed data
		 *     - Any relevant metadata from the ingestion process
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Neither datasetId nor datasetName provided
		 *     - **409 Conflict**: Error during memify operation
		 *     - **403 Forbidden**: User doesn't have permission to use dataset
		 *
		 *     ## Notes
		 *     - To memify datasets not owned by the user, use dataset_id (when ENABLE_BACKEND_ACCESS_CONTROL is set to True)
		 *     - datasetId value can only be the UUID of an already existing dataset
		 */
		post: operations["memify_api_v1_memify_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Search History
		 * @description Get search history for the authenticated user.
		 *
		 *     This endpoint retrieves the search history for the authenticated user,
		 *     returning a list of previously executed searches with their timestamps.
		 *
		 *     ## Response
		 *     Returns a list of search history items containing:
		 *     - **id**: Unique identifier for the search
		 *     - **text**: The search query text
		 *     - **user**: User who performed the search
		 *     - **created_at**: When the search was performed
		 *
		 *     ## Error Codes
		 *     - **500 Internal Server Error**: Error retrieving search history
		 */
		get: operations["get_search_history_api_v1_search_get"];
		put?: never;
		/**
		 * Search
		 * @description Search for nodes in the graph database.
		 *
		 *     This endpoint performs semantic search across the knowledge graph to find
		 *     relevant nodes based on the provided query. It supports different search
		 *     types and can be scoped to specific datasets.
		 *
		 *     ## Request Parameters
		 *     - **search_type** (SearchType): Type of search to perform
		 *     - **datasets** (Optional[List[str]]): List of dataset names to search within
		 *     - **dataset_ids** (Optional[List[UUID]]): List of dataset UUIDs to search within
		 *     - **query** (str): The search query string
		 *     - **system_prompt** Optional[str]: System prompt to be used for Completion type searches in Cognee
		 *     - **node_name** Optional[list[str]]: Filter results to specific node_sets defined in the add pipeline (for targeted search).
		 *     - **top_k** (Optional[int]): Maximum number of results to return (default: 10)
		 *     - **only_context** bool: Set to true to only return context Cognee will be sending to LLM in Completion type searches. This will be returned instead of LLM calls for completion type searches.
		 *
		 *     ## Response
		 *     Returns a list of search results containing relevant nodes from the graph.
		 *
		 *     ## Error Codes
		 *     - **409 Conflict**: Error during search operation
		 *     - **403 Forbidden**: User doesn't have permission to search datasets (returns empty list)
		 *
		 *     ## Notes
		 *     - Datasets sent by name will only map to datasets owned by the request sender
		 *     - To search datasets not owned by the request sender, dataset UUID is needed
		 *     - If permission is denied, returns empty list instead of error
		 */
		post: operations["search_api_v1_search_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/permissions/datasets/{principal_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Give Datasets Permission To Principal
		 * @description Grant permission on datasets to a principal (user or role).
		 *
		 *     This endpoint allows granting specific permissions on one or more datasets
		 *     to a principal (which can be a user or role). The authenticated user must
		 *     have appropriate permissions to grant access to the specified datasets.
		 *
		 *     ## Path Parameters
		 *     - **principal_id** (UUID): The UUID of the principal (user or role) to grant permission to
		 *
		 *     ## Request Parameters
		 *     - **permission_name** (str): The name of the permission to grant (e.g., "read", "write", "delete")
		 *     - **dataset_ids** (List[UUID]): List of dataset UUIDs to grant permission on
		 *
		 *     ## Response
		 *     Returns a success message indicating permission was assigned.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid request parameters
		 *     - **403 Forbidden**: User doesn't have permission to grant access
		 *     - **500 Internal Server Error**: Error granting permission
		 */
		post: operations["give_datasets_permission_to_principal_api_v1_permissions_datasets__principal_id__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/permissions/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Role
		 * @description Create a new role.
		 *
		 *     This endpoint creates a new role with the specified name. Roles are used
		 *     to group permissions and can be assigned to users to manage access control
		 *     more efficiently. The authenticated user becomes the owner of the created role.
		 *
		 *     ## Request Parameters
		 *     - **role_name** (str): The name of the role to create
		 *
		 *     ## Response
		 *     Returns a success message indicating the role was created.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid role name or role already exists
		 *     - **500 Internal Server Error**: Error creating the role
		 */
		post: operations["create_role_api_v1_permissions_roles_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/permissions/users/{user_id}/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add User To Role
		 * @description Add a user to a role.
		 *
		 *     This endpoint assigns a user to a specific role, granting them all the
		 *     permissions associated with that role. The authenticated user must be
		 *     the owner of the role or have appropriate administrative permissions.
		 *
		 *     ## Path Parameters
		 *     - **user_id** (UUID): The UUID of the user to add to the role
		 *
		 *     ## Request Parameters
		 *     - **role_id** (UUID): The UUID of the role to assign the user to
		 *
		 *     ## Response
		 *     Returns a success message indicating the user was added to the role.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid user or role ID
		 *     - **403 Forbidden**: User doesn't have permission to assign roles
		 *     - **404 Not Found**: User or role doesn't exist
		 *     - **500 Internal Server Error**: Error adding user to role
		 */
		post: operations["add_user_to_role_api_v1_permissions_users__user_id__roles_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/permissions/users/{user_id}/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add User To Tenant
		 * @description Add a user to a tenant.
		 *
		 *     This endpoint assigns a user to a specific tenant, allowing them to access
		 *     resources and data associated with that tenant. The authenticated user must
		 *     be the owner of the tenant or have appropriate administrative permissions.
		 *
		 *     ## Path Parameters
		 *     - **user_id** (UUID): The UUID of the user to add to the tenant
		 *
		 *     ## Request Parameters
		 *     - **tenant_id** (UUID): The UUID of the tenant to assign the user to
		 *
		 *     ## Response
		 *     Returns a success message indicating the user was added to the tenant.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid user or tenant ID
		 *     - **403 Forbidden**: User doesn't have permission to assign tenants
		 *     - **404 Not Found**: User or tenant doesn't exist
		 *     - **500 Internal Server Error**: Error adding user to tenant
		 */
		post: operations["add_user_to_tenant_api_v1_permissions_users__user_id__tenants_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/permissions/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Tenant
		 * @description Create a new tenant.
		 *
		 *     This endpoint creates a new tenant with the specified name. Tenants are used
		 *     to organize users and resources in multi-tenant environments, providing
		 *     isolation and access control between different groups or organizations.
		 *
		 *     ## Request Parameters
		 *     - **tenant_name** (str): The name of the tenant to create
		 *
		 *     ## Response
		 *     Returns a success message indicating the tenant was created.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid tenant name or tenant already exists
		 *     - **500 Internal Server Error**: Error creating the tenant
		 */
		post: operations["create_tenant_api_v1_permissions_tenants_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Datasets
		 * @description Get all datasets accessible to the authenticated user.
		 *
		 *     This endpoint retrieves all datasets that the authenticated user has
		 *     read permissions for. The datasets are returned with their metadata
		 *     including ID, name, creation time, and owner information.
		 *
		 *     ## Response
		 *     Returns a list of dataset objects containing:
		 *     - **id**: Unique dataset identifier
		 *     - **name**: Dataset name
		 *     - **created_at**: When the dataset was created
		 *     - **updated_at**: When the dataset was last updated
		 *     - **owner_id**: ID of the dataset owner
		 *
		 *     ## Error Codes
		 *     - **418 I'm a teapot**: Error retrieving datasets
		 */
		get: operations["get_datasets_api_v1_datasets_get"];
		put?: never;
		/**
		 * Create New Dataset
		 * @description Create a new dataset or return existing dataset with the same name.
		 *
		 *     This endpoint creates a new dataset with the specified name. If a dataset
		 *     with the same name already exists for the user, it returns the existing
		 *     dataset instead of creating a duplicate. The user is automatically granted
		 *     all permissions (read, write, share, delete) on the created dataset.
		 *
		 *     ## Request Parameters
		 *     - **dataset_data** (DatasetCreationPayload): Dataset creation parameters containing:
		 *       - **name**: The name for the new dataset
		 *
		 *     ## Response
		 *     Returns the created or existing dataset object containing:
		 *     - **id**: Unique dataset identifier
		 *     - **name**: Dataset name
		 *     - **created_at**: When the dataset was created
		 *     - **updated_at**: When the dataset was last updated
		 *     - **owner_id**: ID of the dataset owner
		 *
		 *     ## Error Codes
		 *     - **418 I'm a teapot**: Error creating dataset
		 */
		post: operations["create_new_dataset_api_v1_datasets_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/{dataset_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Dataset
		 * @description Delete a dataset by its ID.
		 *
		 *     This endpoint permanently deletes a dataset and all its associated data.
		 *     The user must have delete permissions on the dataset to perform this operation.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset to delete
		 *
		 *     ## Response
		 *     No content returned on successful deletion.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist or user doesn't have access
		 *     - **500 Internal Server Error**: Error during deletion
		 */
		delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/{dataset_id}/data/{data_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Data
		 * @description Delete a specific data item from a dataset.
		 *
		 *     This endpoint removes a specific data item from a dataset while keeping
		 *     the dataset itself intact. The user must have delete permissions on the
		 *     dataset to perform this operation.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset containing the data
		 *     - **data_id** (UUID): The unique identifier of the data item to delete
		 *
		 *     ## Response
		 *     No content returned on successful deletion.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset or data item doesn't exist, or user doesn't have access
		 *     - **500 Internal Server Error**: Error during deletion
		 */
		delete: operations["delete_data_api_v1_datasets__dataset_id__data__data_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/{dataset_id}/graph": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Dataset Graph
		 * @description Get the knowledge graph visualization for a dataset.
		 *
		 *     This endpoint retrieves the knowledge graph data for a specific dataset,
		 *     including nodes and edges that represent the relationships between entities
		 *     in the dataset. The graph data is formatted for visualization purposes.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset
		 *
		 *     ## Response
		 *     Returns the graph data containing:
		 *     - **nodes**: List of graph nodes with id, label, and properties
		 *     - **edges**: List of graph edges with source, target, and label
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist or user doesn't have access
		 *     - **500 Internal Server Error**: Error retrieving graph data
		 */
		get: operations["get_dataset_graph_api_v1_datasets__dataset_id__graph_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/{dataset_id}/data": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Dataset Data
		 * @description Get all data items in a dataset.
		 *
		 *     This endpoint retrieves all data items (documents, files, etc.) that belong
		 *     to a specific dataset. Each data item includes metadata such as name, type,
		 *     creation time, and storage location.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset
		 *
		 *     ## Response
		 *     Returns a list of data objects containing:
		 *     - **id**: Unique data item identifier
		 *     - **name**: Data item name
		 *     - **created_at**: When the data was added
		 *     - **updated_at**: When the data was last updated
		 *     - **extension**: File extension
		 *     - **mime_type**: MIME type of the data
		 *     - **raw_data_location**: Storage location of the raw data
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist or user doesn't have access
		 *     - **500 Internal Server Error**: Error retrieving data
		 */
		get: operations["get_dataset_data_api_v1_datasets__dataset_id__data_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Dataset Status
		 * @description Get the processing status of datasets.
		 *
		 *     This endpoint retrieves the current processing status of one or more datasets,
		 *     indicating whether they are being processed, have completed processing, or
		 *     encountered errors during pipeline execution.
		 *
		 *     ## Query Parameters
		 *     - **dataset** (List[UUID]): List of dataset UUIDs to check status for
		 *
		 *     ## Response
		 *     Returns a dictionary mapping dataset IDs to their processing status:
		 *     - **pending**: Dataset is queued for processing
		 *     - **running**: Dataset is currently being processed
		 *     - **completed**: Dataset processing completed successfully
		 *     - **failed**: Dataset processing encountered an error
		 *
		 *     ## Error Codes
		 *     - **500 Internal Server Error**: Error retrieving status information
		 */
		get: operations["get_dataset_status_api_v1_datasets_status_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/datasets/{dataset_id}/data/{data_id}/raw": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Raw Data
		 * @description Download the raw data file for a specific data item.
		 *
		 *     This endpoint allows users to download the original, unprocessed data file
		 *     for a specific data item within a dataset. The file is returned as a direct
		 *     download with appropriate headers.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset containing the data
		 *     - **data_id** (UUID): The unique identifier of the data item to download
		 *
		 *     ## Response
		 *     Returns the raw data file as a downloadable response.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset or data item doesn't exist, or user doesn't have access
		 *     - **500 Internal Server Error**: Error accessing the raw data file
		 */
		get: operations["get_raw_data_api_v1_datasets__dataset_id__data__data_id__raw_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Settings
		 * @description Get the current system settings.
		 *
		 *     This endpoint retrieves the current configuration settings for the system,
		 *     including LLM (Large Language Model) configuration and vector database
		 *     configuration. These settings determine how the system processes and stores data.
		 *
		 *     ## Response
		 *     Returns the current system settings containing:
		 *     - **llm**: LLM configuration (provider, model, API key)
		 *     - **vector_db**: Vector database configuration (provider, URL, API key)
		 *
		 *     ## Error Codes
		 *     - **500 Internal Server Error**: Error retrieving settings
		 */
		get: operations["get_settings_api_v1_settings_get"];
		put?: never;
		/**
		 * Save Settings
		 * @description Save or update system settings.
		 *
		 *     This endpoint allows updating the system configuration settings. You can
		 *     update either the LLM configuration, vector database configuration, or both.
		 *     Only provided settings will be updated; others remain unchanged.
		 *
		 *     ## Request Parameters
		 *     - **llm** (Optional[LLMConfigInputDTO]): LLM configuration (provider, model, API key)
		 *     - **vector_db** (Optional[VectorDBConfigInputDTO]): Vector database configuration (provider, URL, API key)
		 *
		 *     ## Response
		 *     No content returned on successful save.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid settings provided
		 *     - **500 Internal Server Error**: Error saving settings
		 */
		post: operations["save_settings_api_v1_settings_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/visualize": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Visualize
		 * @description Generate an HTML visualization of the dataset's knowledge graph.
		 *
		 *     This endpoint creates an interactive HTML visualization of the knowledge graph
		 *     for a specific dataset. The visualization displays nodes and edges representing
		 *     entities and their relationships, allowing users to explore the graph structure
		 *     visually.
		 *
		 *     ## Query Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset to visualize
		 *
		 *     ## Response
		 *     Returns an HTML page containing the interactive graph visualization.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist
		 *     - **403 Forbidden**: User doesn't have permission to read the dataset
		 *     - **500 Internal Server Error**: Error generating visualization
		 *
		 *     ## Notes
		 *     - User must have read permissions on the dataset
		 *     - Visualization is interactive and allows graph exploration
		 */
		get: operations["visualize_api_v1_visualize_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/delete": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete
		 * @description Delete data by its ID from the specified dataset.
		 *
		 *     Args:
		 *         data_id: The UUID of the data to delete
		 *         dataset_id: The UUID of the dataset containing the data
		 *         mode: "soft" (default) or "hard" - hard mode also deletes degree-one entity nodes
		 *         user: Authenticated user
		 *
		 *     Returns:
		 *         JSON response indicating success or failure
		 */
		delete: operations["delete_api_v1_delete_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/update": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update
		 * @description Update data in a dataset.
		 *
		 *     This endpoint updates existing documents in a specified dataset by providing the data_id of the existing document
		 *     to update and the new document with the changes as the data.
		 *     The document is updated, analyzed, and the changes are integrated into the knowledge graph.
		 *
		 *     ## Request Parameters
		 *     - **data_id** (UUID): UUID of the document to update in Cognee memory
		 *     - **data** (List[UploadFile]): List of files to upload.
		 *     - **datasetId** (Optional[UUID]): UUID of an already existing dataset
		 *     - **node_set** Optional[list[str]]: List of node identifiers for graph organization and access control.
		 *              Used for grouping related data points in the knowledge graph.
		 *
		 *     ## Response
		 *     Returns information about the add operation containing:
		 *     - Status of the operation
		 *     - Details about the processed data
		 *     - Any relevant metadata from the ingestion process
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Neither datasetId nor datasetName provided
		 *     - **409 Conflict**: Error during add operation
		 *     - **403 Forbidden**: User doesn't have permission to add to dataset
		 *
		 *     ## Notes
		 *     - To add data to datasets not owned by the user, use dataset_id (when ENABLE_BACKEND_ACCESS_CONTROL is set to True)
		 *     - datasetId value can only be the UUID of an already existing dataset
		 */
		patch: operations["update_api_v1_update_patch"];
		trace?: never;
	};
	"/api/v1/responses/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Response
		 * @description OpenAI-compatible responses endpoint with function calling support.
		 *
		 *     This endpoint provides OpenAI-compatible API responses with integrated
		 *     function calling capabilities for Cognee operations.
		 *
		 *     ## Request Parameters
		 *     - **input** (str): The input text to process
		 *     - **model** (str): The model to use for processing
		 *     - **tools** (Optional[List[Dict]]): Available tools for function calling
		 *     - **tool_choice** (Any): Tool selection strategy (default: "auto")
		 *     - **temperature** (float): Response randomness (default: 1.0)
		 *
		 *     ## Response
		 *     Returns an OpenAI-compatible response body with function call results.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid request parameters
		 *     - **500 Internal Server Error**: Error processing request
		 *
		 *     ## Notes
		 *     - Compatible with OpenAI API format
		 *     - Supports function calling with Cognee tools
		 *     - Uses default tools if none provided
		 */
		post: operations["create_response_api_v1_responses__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/sync": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sync To Cloud
		 * @description Sync local data to Cognee Cloud.
		 *
		 *     This endpoint triggers synchronization of local Cognee data to your cloud instance.
		 *     It uploads your local datasets, knowledge graphs, and processed data to the cloud
		 *     for backup, sharing, or cloud-based processing.
		 *
		 *     ## Request Body (JSON)
		 *     ```json
		 *     {
		 *         "dataset_ids": ["123e4567-e89b-12d3-a456-426614174000", "456e7890-e12b-34c5-d678-901234567000"]
		 *     }
		 *     ```
		 *
		 *     ## Response
		 *     Returns immediate response for the sync operation:
		 *     - **run_id**: Unique identifier for tracking the background sync operation
		 *     - **status**: Always "started" (operation runs in background)
		 *     - **dataset_ids**: List of dataset IDs being synced
		 *     - **dataset_names**: List of dataset names being synced
		 *     - **message**: Description of the background operation
		 *     - **timestamp**: When the sync was initiated
		 *     - **user_id**: User who initiated the sync
		 *
		 *     ## Cloud Sync Features
		 *     - **Automatic Authentication**: Uses your Cognee Cloud credentials
		 *     - **Data Compression**: Optimizes transfer size for faster uploads
		 *     - **Smart Sync**: Automatically handles data updates efficiently
		 *     - **Progress Tracking**: Monitor sync status with sync_id
		 *     - **Error Recovery**: Automatic retry for failed transfers
		 *     - **Data Validation**: Ensures data integrity during transfer
		 *
		 *     ## Example Usage
		 *     ```bash
		 *     # Sync multiple datasets to cloud by IDs (JSON request)
		 *     curl -X POST "http://localhost:8000/api/v1/sync" \
		 *       -H "Content-Type: application/json" \
		 *       -H "Cookie: auth_token=your-token" \
		 *       -d '{"dataset_ids": ["123e4567-e89b-12d3-a456-426614174000", "456e7890-e12b-34c5-d678-901234567000"]}'
		 *
		 *     # Sync all user datasets (empty request body or null dataset_ids)
		 *     curl -X POST "http://localhost:8000/api/v1/sync" \
		 *       -H "Content-Type: application/json" \
		 *       -H "Cookie: auth_token=your-token" \
		 *       -d '{}'
		 *     ```
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid dataset_ids format
		 *     - **401 Unauthorized**: Invalid or missing authentication
		 *     - **403 Forbidden**: User doesn't have permission to access dataset
		 *     - **404 Not Found**: Dataset not found
		 *     - **409 Conflict**: Sync operation conflict or cloud service unavailable
		 *     - **413 Payload Too Large**: Dataset too large for current cloud plan
		 *     - **429 Too Many Requests**: Rate limit exceeded
		 *
		 *     ## Notes
		 *     - Sync operations run in the background - you get an immediate response
		 *     - Use the returned run_id to track progress (status API coming soon)
		 *     - Large datasets are automatically chunked for efficient transfer
		 *     - Cloud storage usage counts against your plan limits
		 *     - The sync will continue even if you close your connection
		 */
		post: operations["sync_to_cloud_api_v1_sync_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/sync/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Sync Status Overview
		 * @description Check if there are any running sync operations for the current user.
		 *
		 *     This endpoint provides a simple check to see if the user has any active sync operations
		 *     without needing to know specific run IDs.
		 *
		 *     ## Response
		 *     Returns a simple status overview:
		 *     - **has_running_sync**: Boolean indicating if there are any running syncs
		 *     - **running_sync_count**: Number of currently running sync operations
		 *     - **latest_running_sync** (optional): Information about the most recent running sync if any exists
		 *
		 *     ## Example Usage
		 *     ```bash
		 *     curl -X GET "http://localhost:8000/api/v1/sync/status" \
		 *       -H "Cookie: auth_token=your-token"
		 *     ```
		 *
		 *     ## Example Responses
		 *
		 *     **No running syncs:**
		 *     ```json
		 *     {
		 *       "has_running_sync": false,
		 *       "running_sync_count": 0
		 *     }
		 *     ```
		 *
		 *     **With running sync:**
		 *     ```json
		 *     {
		 *       "has_running_sync": true,
		 *       "running_sync_count": 1,
		 *       "latest_running_sync": {
		 *         "run_id": "12345678-1234-5678-9012-123456789012",
		 *         "dataset_name": "My Dataset",
		 *         "progress_percentage": 45,
		 *         "created_at": "2025-01-01T00:00:00Z"
		 *       }
		 *     }
		 *     ```
		 */
		get: operations["get_sync_status_overview_api_v1_sync_status_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/code-pipeline/index": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Code Pipeline Index
		 * @description Run indexation on a code repository.
		 *
		 *     This endpoint processes a code repository to create a knowledge graph
		 *     of the codebase structure, dependencies, and relationships.
		 *
		 *     ## Request Parameters
		 *     - **repo_path** (str): Path to the code repository
		 *     - **include_docs** (bool): Whether to include documentation files (default: false)
		 *
		 *     ## Response
		 *     No content returned. Processing results are logged.
		 *
		 *     ## Error Codes
		 *     - **409 Conflict**: Error during indexation process
		 */
		post: operations["code_pipeline_index_api_v1_code_pipeline_index_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/code-pipeline/retrieve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Code Pipeline Retrieve
		 * @description Retrieve context from the code knowledge graph.
		 *
		 *     This endpoint searches the indexed code repository to find relevant
		 *     context based on the provided query.
		 *
		 *     ## Request Parameters
		 *     - **query** (str): Search query for code context
		 *     - **full_input** (str): Full input text for processing
		 *
		 *     ## Response
		 *     Returns a list of relevant code files and context as JSON.
		 *
		 *     ## Error Codes
		 *     - **409 Conflict**: Error during retrieval process
		 */
		post: operations["code_pipeline_retrieve_api_v1_code_pipeline_retrieve_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Users:Current User */
		get: operations["users_current_user_api_v1_users_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Users:Patch Current User */
		patch: operations["users_patch_current_user_api_v1_users_me_patch"];
		trace?: never;
	};
	"/api/v1/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Users:User */
		get: operations["users_user_api_v1_users__id__get"];
		put?: never;
		post?: never;
		/** Users:Delete User */
		delete: operations["users_delete_user_api_v1_users__id__delete"];
		options?: never;
		head?: never;
		/** Users:Patch User */
		patch: operations["users_patch_user_api_v1_users__id__patch"];
		trace?: never;
	};
	"/api/v1/notebooks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Notebooks Endpoint */
		get: operations["get_notebooks_endpoint_api_v1_notebooks_get"];
		put?: never;
		/** Create Notebook Endpoint */
		post: operations["create_notebook_endpoint_api_v1_notebooks_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/notebooks/{notebook_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update Notebook Endpoint */
		put: operations["update_notebook_endpoint_api_v1_notebooks__notebook_id__put"];
		post?: never;
		/** Delete Notebook Endpoint */
		delete: operations["delete_notebook_endpoint_api_v1_notebooks__notebook_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/notebooks/{notebook_id}/{cell_id}/run": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Run Notebook Cell Endpoint */
		post: operations["run_notebook_cell_endpoint_api_v1_notebooks__notebook_id___cell_id__run_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/checks/connection": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get Connection Check Endpoint */
		post: operations["get_connection_check_endpoint_api_v1_checks_connection_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** Body_add_api_v1_add_post */
		Body_add_api_v1_add_post: {
			/** Data */
			data?: string[];
			/** Datasetname */
			datasetName?: string | null;
			/**
			 * Datasetid
			 * @example
			 */
			datasetId?: string | "" | null;
			/**
			 * Node Set
			 * @default [
			 *       ""
			 *     ]
			 */
			node_set: string[] | null;
		};
		/** Body_auth_cookie_login_api_v1_auth_login_post */
		Body_auth_cookie_login_api_v1_auth_login_post: {
			/** Grant Type */
			grant_type?: string | null;
			/** Username */
			username: string;
			/**
			 * Password
			 * Format: password
			 */
			password: string;
			/**
			 * Scope
			 * @default
			 */
			scope: string;
			/** Client Id */
			client_id?: string | null;
			/**
			 * Client Secret
			 * Format: password
			 */
			client_secret?: string | null;
		};
		/** Body_reset_forgot_password_api_v1_auth_forgot_password_post */
		Body_reset_forgot_password_api_v1_auth_forgot_password_post: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
		};
		/** Body_reset_reset_password_api_v1_auth_reset_password_post */
		Body_reset_reset_password_api_v1_auth_reset_password_post: {
			/** Token */
			token: string;
			/** Password */
			password: string;
		};
		/** Body_update_api_v1_update_patch */
		Body_update_api_v1_update_patch: {
			/** Data */
			data?: string[];
			/**
			 * Node Set
			 * @default [
			 *       ""
			 *     ]
			 */
			node_set: string[] | null;
		};
		/** Body_verify_request_token_api_v1_auth_request_verify_token_post */
		Body_verify_request_token_api_v1_auth_request_verify_token_post: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
		};
		/** Body_verify_verify_api_v1_auth_verify_post */
		Body_verify_verify_api_v1_auth_verify_post: {
			/** Token */
			token: string;
		};
		/**
		 * ChatUsage
		 * @description Token usage information
		 */
		ChatUsage: {
			/**
			 * Prompt Tokens
			 * @default 0
			 */
			prompt_tokens: number;
			/**
			 * Completion Tokens
			 * @default 0
			 */
			completion_tokens: number;
			/**
			 * Total Tokens
			 * @default 0
			 */
			total_tokens: number;
		};
		/** CodePipelineIndexPayloadDTO */
		CodePipelineIndexPayloadDTO: {
			/** Repopath */
			repoPath: string;
			/**
			 * Includedocs
			 * @default false
			 */
			includeDocs: boolean;
		};
		/** CodePipelineRetrievePayloadDTO */
		CodePipelineRetrievePayloadDTO: {
			/** Query */
			query: string;
			/** Fullinput */
			fullInput: string;
		};
		/**
		 * CogneeModel
		 * @description Enum for supported model types
		 * @enum {string}
		 */
		CogneeModel: "cognee-v1";
		/** CognifyPayloadDTO */
		CognifyPayloadDTO: {
			/** Datasets */
			datasets?: string[] | null;
			/**
			 * Datasetids
			 * @example []
			 */
			datasetIds?: string[] | null;
			/**
			 * Runinbackground
			 * @default false
			 */
			runInBackground: boolean | null;
			/**
			 * Customprompt
			 * @description Custom prompt for entity extraction and graph generation
			 * @default
			 */
			customPrompt: string | null;
		};
		/** CombinedSearchResult */
		CombinedSearchResult: {
			/** Result */
			result: unknown | null;
			/** Context */
			context: {
				[key: string]: unknown;
			};
			/**
			 * Graphs
			 * @default {}
			 */
			graphs: {
				[key: string]: unknown;
			} | null;
			/** Datasets */
			datasets?: components["schemas"]["SearchResultDataset"][] | null;
		};
		/** ConfigChoice */
		ConfigChoice: {
			/** Value */
			value: string;
			/** Label */
			label: string;
		};
		/** DataDTO */
		DataDTO: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
			/** Updatedat */
			updatedAt?: string | null;
			/** Extension */
			extension: string;
			/** Mimetype */
			mimeType: string;
			/** Rawdatalocation */
			rawDataLocation: string;
			/**
			 * Datasetid
			 * Format: uuid
			 */
			datasetId: string;
		};
		/** DatasetCreationPayload */
		DatasetCreationPayload: {
			/** Name */
			name: string;
		};
		/** DatasetDTO */
		DatasetDTO: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
			/** Updatedat */
			updatedAt?: string | null;
			/**
			 * Ownerid
			 * Format: uuid
			 */
			ownerId: string;
		};
		/** ErrorModel */
		ErrorModel: {
			/** Detail */
			detail:
				| string
				| {
						[key: string]: string;
				  };
		};
		/** ErrorResponseDTO */
		ErrorResponseDTO: {
			/** Message */
			message: string;
		};
		/**
		 * Function
		 * @description Function definition compatible with OpenAI's format
		 */
		Function: {
			/** Name */
			name: string;
			/** Description */
			description: string;
			parameters: components["schemas"]["FunctionParameters"];
		};
		/**
		 * FunctionCall
		 * @description Function call made by the assistant
		 */
		FunctionCall: {
			/** Name */
			name: string;
			/** Arguments */
			arguments: string;
		};
		/**
		 * FunctionParameters
		 * @description JSON Schema for function parameters
		 */
		FunctionParameters: {
			/**
			 * Type
			 * @default object
			 */
			type: string;
			/** Properties */
			properties: {
				[key: string]: {
					[key: string]: unknown;
				};
			};
			/** Required */
			required?: string[] | null;
		};
		/** GraphDTO */
		GraphDTO: {
			/** Nodes */
			nodes: components["schemas"]["GraphNodeDTO"][];
			/** Edges */
			edges: components["schemas"]["GraphEdgeDTO"][];
		};
		/** GraphEdgeDTO */
		GraphEdgeDTO: {
			/**
			 * Source
			 * Format: uuid
			 */
			source: string;
			/**
			 * Target
			 * Format: uuid
			 */
			target: string;
			/** Label */
			label: string;
		};
		/** GraphNodeDTO */
		GraphNodeDTO: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Label */
			label: string;
			/** Properties */
			properties: {
				[key: string]: unknown;
			};
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** LLMConfigInputDTO */
		LLMConfigInputDTO: {
			/** Provider */
			provider: "openai" | "ollama" | "anthropic" | "gemini" | "mistral";
			/** Model */
			model: string;
			/** Apikey */
			apiKey: string;
		};
		/** LLMConfigOutputDTO */
		LLMConfigOutputDTO: {
			/** Apikey */
			apiKey: string;
			/** Model */
			model: string;
			/** Provider */
			provider: string;
			/** Endpoint */
			endpoint: string | null;
			/** Apiversion */
			apiVersion: string | null;
			/** Models */
			models: {
				[key: string]: components["schemas"]["ConfigChoice"][];
			};
			/** Providers */
			providers: components["schemas"]["ConfigChoice"][];
		};
		/** MemifyPayloadDTO */
		MemifyPayloadDTO: {
			/**
			 * Extractiontasks
			 * @example []
			 */
			extractionTasks?: string[] | null;
			/**
			 * Enrichmenttasks
			 * @example []
			 */
			enrichmentTasks?: string[] | null;
			/**
			 * Data
			 * @default
			 */
			data: string | null;
			/** Datasetname */
			datasetName?: string | null;
			/**
			 * Datasetid
			 * @example
			 */
			datasetId?: string | "" | null;
			/**
			 * Nodename
			 * @example []
			 */
			nodeName?: string[] | null;
			/**
			 * Runinbackground
			 * @default false
			 */
			runInBackground: boolean | null;
		};
		/** NotebookCell */
		NotebookCell: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Type
			 * @enum {string}
			 */
			type: "markdown" | "code";
			/** Name */
			name: string;
			/** Content */
			content: string;
		};
		/** NotebookData */
		NotebookData: {
			/** Name */
			name: string | null;
			/**
			 * Cells
			 * @default []
			 */
			cells: components["schemas"]["NotebookCell"][] | null;
		};
		/**
		 * PipelineRunStatus
		 * @enum {string}
		 */
		PipelineRunStatus:
			| "DATASET_PROCESSING_INITIATED"
			| "DATASET_PROCESSING_STARTED"
			| "DATASET_PROCESSING_COMPLETED"
			| "DATASET_PROCESSING_ERRORED";
		/**
		 * ResponseBody
		 * @description Response body for the new responses endpoint
		 */
		ResponseBody: {
			/** Id */
			id?: string;
			/** Created */
			created?: number;
			/** Model */
			model: string;
			/**
			 * Object
			 * @default response
			 */
			object: string;
			/**
			 * Status
			 * @default completed
			 */
			status: string;
			/** Toolcalls */
			toolCalls: components["schemas"]["ResponseToolCall"][];
			usage?: components["schemas"]["ChatUsage"] | null;
			/** Metadata */
			metadata?: {
				[key: string]: unknown;
			};
		};
		/**
		 * ResponseRequest
		 * @description Request body for the new responses endpoint (OpenAI Responses API format)
		 */
		ResponseRequest: {
			/** @default cognee-v1 */
			model: components["schemas"]["CogneeModel"];
			/** Input */
			input: string;
			/** Tools */
			tools?: components["schemas"]["ToolFunction"][] | null;
			/**
			 * Toolchoice
			 * @default auto
			 */
			toolChoice:
				| string
				| {
						[key: string]: unknown;
				  }
				| null;
			/** User */
			user?: string | null;
			/**
			 * Temperature
			 * @default 1
			 */
			temperature: number | null;
			/** Maxcompletiontokens */
			maxCompletionTokens?: number | null;
		};
		/**
		 * ResponseToolCall
		 * @description Tool call in a response
		 */
		ResponseToolCall: {
			/** Id */
			id?: string;
			/**
			 * Type
			 * @default function
			 */
			type: string;
			function: components["schemas"]["FunctionCall"];
			output?: components["schemas"]["ToolCallOutput"] | null;
		};
		/** RunCodeData */
		RunCodeData: {
			/** Content */
			content: string;
		};
		/** SearchHistoryItem */
		SearchHistoryItem: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Text */
			text: string;
			/** User */
			user: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
		};
		/** SearchPayloadDTO */
		SearchPayloadDTO: {
			/** @default GRAPH_COMPLETION */
			searchType: components["schemas"]["SearchType"];
			/** Datasets */
			datasets?: string[] | null;
			/**
			 * Datasetids
			 * @example []
			 */
			datasetIds?: string[] | null;
			/**
			 * Query
			 * @default What is in the document?
			 */
			query: string;
			/**
			 * Systemprompt
			 * @default Answer the question using the provided context. Be as brief as possible.
			 */
			systemPrompt: string | null;
			/**
			 * Nodename
			 * @example []
			 */
			nodeName?: string[] | null;
			/**
			 * Topk
			 * @default 10
			 */
			topK: number | null;
			/**
			 * Onlycontext
			 * @default false
			 */
			onlyContext: boolean;
			/**
			 * Usecombinedcontext
			 * @default false
			 */
			useCombinedContext: boolean;
		};
		/** SearchResult */
		SearchResult: {
			/** Search Result */
			search_result: unknown;
			/** Dataset Id */
			dataset_id: string | null;
			/** Dataset Name */
			dataset_name: string | null;
		};
		/** SearchResultDataset */
		SearchResultDataset: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
		};
		/**
		 * SearchType
		 * @enum {string}
		 */
		SearchType:
			| "SUMMARIES"
			| "CHUNKS"
			| "RAG_COMPLETION"
			| "GRAPH_COMPLETION"
			| "GRAPH_SUMMARY_COMPLETION"
			| "CODE"
			| "CYPHER"
			| "NATURAL_LANGUAGE"
			| "GRAPH_COMPLETION_COT"
			| "GRAPH_COMPLETION_CONTEXT_EXTENSION"
			| "FEELING_LUCKY"
			| "FEEDBACK"
			| "TEMPORAL"
			| "CODING_RULES"
			| "CHUNKS_LEXICAL";
		/** SettingsDTO */
		SettingsDTO: {
			llm: components["schemas"]["LLMConfigOutputDTO"];
			vectorDb: components["schemas"]["VectorDBConfigOutputDTO"];
		};
		/** SettingsPayloadDTO */
		SettingsPayloadDTO: {
			llm?: components["schemas"]["LLMConfigInputDTO"] | null;
			vectorDb?: components["schemas"]["VectorDBConfigInputDTO"] | null;
		};
		/**
		 * SyncRequest
		 * @description Request model for sync operations.
		 */
		SyncRequest: {
			/** Datasetids */
			datasetIds?: string[] | null;
		};
		/**
		 * SyncResponse
		 * @description Response model for sync operations.
		 */
		SyncResponse: {
			/** Run Id */
			run_id: string;
			/** Status */
			status: string;
			/** Dataset Ids */
			dataset_ids: string[];
			/** Dataset Names */
			dataset_names: string[];
			/** Message */
			message: string;
			/** Timestamp */
			timestamp: string;
			/** User Id */
			user_id: string;
		};
		/**
		 * ToolCallOutput
		 * @description Output of a tool call in the responses API
		 */
		ToolCallOutput: {
			/**
			 * Status
			 * @default success
			 */
			status: string;
			/** Data */
			data?: {
				[key: string]: unknown;
			} | null;
		};
		/**
		 * ToolFunction
		 * @description Tool function wrapper (for OpenAI compatibility)
		 */
		ToolFunction: {
			/**
			 * Type
			 * @default function
			 */
			type: string;
			function: components["schemas"]["Function"];
		};
		/** UserCreate */
		UserCreate: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
			/**
			 * Is Active
			 * @default true
			 */
			is_active: boolean | null;
			/**
			 * Is Superuser
			 * @default false
			 */
			is_superuser: boolean | null;
			/**
			 * Is Verified
			 * @default true
			 */
			is_verified: boolean;
			/** Tenant Id */
			tenant_id?: string | null;
		};
		/** UserRead */
		UserRead: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/**
			 * Is Active
			 * @default true
			 */
			is_active: boolean;
			/**
			 * Is Superuser
			 * @default false
			 */
			is_superuser: boolean;
			/**
			 * Is Verified
			 * @default false
			 */
			is_verified: boolean;
			/** Tenant Id */
			tenant_id?: string | null;
		};
		/** UserUpdate */
		UserUpdate: {
			/** Password */
			password?: string | null;
			/** Email */
			email?: string | null;
			/** Is Active */
			is_active?: boolean | null;
			/** Is Superuser */
			is_superuser?: boolean | null;
			/** Is Verified */
			is_verified?: boolean | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/** VectorDBConfigInputDTO */
		VectorDBConfigInputDTO: {
			/** Provider */
			provider: "lancedb" | "chromadb" | "pgvector";
			/** Url */
			url: string;
			/** Apikey */
			apiKey: string;
		};
		/** VectorDBConfigOutputDTO */
		VectorDBConfigOutputDTO: {
			/** Apikey */
			apiKey: string;
			/** Url */
			url: string;
			/** Provider */
			provider: string;
			/** Providers */
			providers: components["schemas"]["ConfigChoice"][];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	health_check_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	detailed_health_check_health_detailed_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	auth_cookie_login_api_v1_auth_login_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_api_v1_auth_login_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	auth_cookie_logout_api_v1_auth_logout_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_me_api_v1_auth_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	register_register_api_v1_auth_register_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	reset_forgot_password_api_v1_auth_forgot_password_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Body_reset_forgot_password_api_v1_auth_forgot_password_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	reset_reset_password_api_v1_auth_reset_password_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Body_reset_reset_password_api_v1_auth_reset_password_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	verify_request_token_api_v1_auth_request_verify_token_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Body_verify_request_token_api_v1_auth_request_verify_token_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	verify_verify_api_v1_auth_verify_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Body_verify_verify_api_v1_auth_verify_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	add_api_v1_add_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["Body_add_api_v1_add_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	cognify_api_v1_cognify_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CognifyPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	memify_api_v1_memify_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["MemifyPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_search_history_api_v1_search_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SearchHistoryItem"][];
				};
			};
		};
	};
	search_api_v1_search_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SearchPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json":
						| components["schemas"]["SearchResult"][]
						| components["schemas"]["CombinedSearchResult"]
						| unknown[];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	give_datasets_permission_to_principal_api_v1_permissions_datasets__principal_id__post: {
		parameters: {
			query: {
				permission_name: string;
			};
			header?: never;
			path: {
				principal_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": string[];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_role_api_v1_permissions_roles_post: {
		parameters: {
			query: {
				role_name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	add_user_to_role_api_v1_permissions_users__user_id__roles_post: {
		parameters: {
			query: {
				role_id: string;
			};
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	add_user_to_tenant_api_v1_permissions_users__user_id__tenants_post: {
		parameters: {
			query: {
				tenant_id: string;
			};
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_tenant_api_v1_permissions_tenants_post: {
		parameters: {
			query: {
				tenant_name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_datasets_api_v1_datasets_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DatasetDTO"][];
				};
			};
		};
	};
	create_new_dataset_api_v1_datasets_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DatasetCreationPayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DatasetDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_dataset_api_v1_datasets__dataset_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponseDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_data_api_v1_datasets__dataset_id__data__data_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
				data_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponseDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dataset_graph_api_v1_datasets__dataset_id__graph_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GraphDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dataset_data_api_v1_datasets__dataset_id__data_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DataDTO"][];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorResponseDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dataset_status_api_v1_datasets_status_get: {
		parameters: {
			query?: {
				dataset?: string[];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: components["schemas"]["PipelineRunStatus"];
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_raw_data_api_v1_datasets__dataset_id__data__data_id__raw_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
				data_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_settings_api_v1_settings_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SettingsDTO"];
				};
			};
		};
	};
	save_settings_api_v1_settings_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SettingsPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	visualize_api_v1_visualize_get: {
		parameters: {
			query: {
				dataset_id: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_api_v1_delete_delete: {
		parameters: {
			query: {
				data_id: string;
				dataset_id: string;
				mode?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	update_api_v1_update_patch: {
		parameters: {
			query: {
				data_id: string;
				dataset_id: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["Body_update_api_v1_update_patch"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_response_api_v1_responses__post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResponseRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseBody"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	sync_to_cloud_api_v1_sync_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SyncRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: components["schemas"]["SyncResponse"];
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_sync_status_overview_api_v1_sync_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	code_pipeline_index_api_v1_code_pipeline_index_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodePipelineIndexPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	code_pipeline_retrieve_api_v1_code_pipeline_retrieve_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodePipelineRetrievePayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					}[];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	users_current_user_api_v1_users_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	users_patch_current_user_api_v1_users_me_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserUpdate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	users_user_api_v1_users__id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a superuser. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The user does not exist. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	users_delete_user_api_v1_users__id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a superuser. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The user does not exist. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	users_patch_user_api_v1_users__id__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserUpdate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Missing token or inactive user. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a superuser. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The user does not exist. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_notebooks_endpoint_api_v1_notebooks_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	create_notebook_endpoint_api_v1_notebooks_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NotebookData"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	update_notebook_endpoint_api_v1_notebooks__notebook_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notebook_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NotebookData"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_notebook_endpoint_api_v1_notebooks__notebook_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notebook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	run_notebook_cell_endpoint_api_v1_notebooks__notebook_id___cell_id__run_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notebook_id: string;
				cell_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RunCodeData"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_connection_check_endpoint_api_v1_checks_connection_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
}
