/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/add": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add Text
		 * @description Add text data to a dataset for processing and knowledge graph construction.
		 *
		 *     This endpoint accepts only text and adds it to a specified dataset for processing. The text is ingested,
		 *     analyzed, and integrated into the knowledge graph.
		 *
		 *     ## Request Parameters
		 *     - **text_data** (List[str]): List of text to process.
		 *     - **datasetName** (Optional[str]): Name of the dataset to add data to
		 *     - **datasetId** (Optional[UUID]): UUID of an already existing dataset
		 *
		 *     Either datasetName or datasetId must be provided.
		 *
		 *     ## Response
		 *     Returns information about the add operation containing:
		 *     - Status of the operation
		 *     - Details about the processed data
		 *     - Any relevant metadata from the ingestion process
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Neither datasetId nor datasetName provided
		 *     - **409 Conflict**: Error during add operation
		 *     - **403 Forbidden**: User doesn't have permission to add to dataset
		 *
		 *     ## Notes
		 *     - To add data to datasets not owned by the user, use dataset_id (when ENABLE_BACKEND_ACCESS_CONTROL is set to True)
		 *     - datasetId value can only be the UUID of an already existing dataset
		 */
		post: operations["add_text_api_add_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cognify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Cognify
		 * @description Transform datasets into structured knowledge graphs through cognitive processing.
		 *
		 *     This endpoint is the core of Cognee's intelligence layer, responsible for converting
		 *     raw text, documents, and data added through the add endpoint into semantic knowledge graphs.
		 *     It performs deep analysis to extract entities, relationships, and insights from ingested content.
		 *
		 *     ## Processing Pipeline
		 *     1. Document classification and permission validation
		 *     2. Text chunking and semantic segmentation
		 *     3. Entity extraction using LLM-powered analysis
		 *     4. Relationship detection and graph construction
		 *     5. Vector embeddings generation for semantic search
		 *     6. Content summarization and indexing
		 *
		 *     ## Request Parameters
		 *     - **datasets** (Optional[List[str]]): List of dataset names to process. Dataset names are resolved to datasets owned by the authenticated user.
		 *     - **dataset_ids** (Optional[List[UUID]]): List of existing dataset UUIDs to process. UUIDs allow processing of datasets not owned by the user (if permitted).
		 *     - **run_in_background** (Optional[bool]): Whether to execute processing asynchronously. Defaults to False (blocking).
		 *     - **custom_prompt** (Optional[str]): Custom prompt for entity extraction and graph generation. If provided, this prompt will be used instead of the default prompts for knowledge graph extraction.
		 *
		 *     ## Response
		 *     - **Blocking execution**: Complete pipeline run information with entity counts, processing duration, and success/failure status
		 *     - **Background execution**: Pipeline run metadata including pipeline_run_id for status monitoring via WebSocket subscription
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: When neither datasets nor dataset_ids are provided, or when specified datasets don't exist
		 *     - **409 Conflict**: When processing fails due to system errors, missing LLM API keys, database connection failures, or corrupted content
		 *
		 *     ## Example Request
		 *     ```json
		 *     {
		 *         "datasets": ["research_papers", "documentation"],
		 *         "run_in_background": false,
		 *         "custom_prompt": "Extract entities focusing on technical concepts and their relationships. Identify key technologies, methodologies, and their interconnections."
		 *     }
		 *     ```
		 *
		 *     ## Notes
		 *     To cognify data in datasets not owned by the user and for which the current user has write permission,
		 *     the dataset_id must be used (when ENABLE_BACKEND_ACCESS_CONTROL is set to True).
		 *
		 *     ## Next Steps
		 *     After successful processing, use the search endpoints to query the generated knowledge graph for insights, relationships, and semantic search.
		 */
		post: operations["cognify_api_cognify_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Search History
		 * @description Get search history for the authenticated user.
		 *
		 *     This endpoint retrieves the search history for the authenticated user,
		 *     returning a list of previously executed searches with their timestamps.
		 *
		 *     ## Response
		 *     Returns a list of search history items containing:
		 *     - **id**: Unique identifier for the search
		 *     - **text**: The search query text
		 *     - **user**: User who performed the search
		 *     - **created_at**: When the search was performed
		 *
		 *     ## Error Codes
		 *     - **500 Internal Server Error**: Error retrieving search history
		 */
		get: operations["get_search_history_api_search_get"];
		put?: never;
		/**
		 * Search
		 * @description Search for nodes in the graph database.
		 *
		 *     This endpoint performs semantic search across the knowledge graph to find
		 *     relevant nodes based on the provided query. It supports different search
		 *     types and can be scoped to specific datasets.
		 *
		 *     ## Request Parameters
		 *     - **search_type** (SearchType): Type of search to perform
		 *     - **datasets** (Optional[List[str]]): List of dataset names to search within
		 *     - **dataset_ids** (Optional[List[UUID]]): List of dataset UUIDs to search within
		 *     - **query** (str): The search query string
		 *     - **system_prompt** Optional[str]: System prompt to be used for Completion type searches in Cognee
		 *     - **node_name** Optional[list[str]]: Filter results to specific node_sets defined in the add pipeline (for targeted search).
		 *     - **top_k** (Optional[int]): Maximum number of results to return (default: 10)
		 *     - **only_context** bool: Set to true to only return context Cognee will be sending to LLM in Completion type searches. This will be returned instead of LLM calls for completion type searches.
		 *
		 *     ## Response
		 *     Returns a list of search results containing relevant nodes from the graph.
		 *
		 *     ## Error Codes
		 *     - **409 Conflict**: Error during search operation
		 *     - **403 Forbidden**: User doesn't have permission to search datasets (returns empty list)
		 *
		 *     ## Notes
		 *     - Datasets sent by name will only map to datasets owned by the request sender
		 *     - To search datasets not owned by the request sender, dataset UUID is needed
		 *     - If permission is denied, returns empty list instead of error
		 */
		post: operations["search_api_search_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/delete": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete
		 * @description Delete data by its ID from the specified dataset.
		 *
		 *     Args:
		 *         data_id: The UUID of the data to delete
		 *         dataset_id: The UUID of the dataset containing the data
		 *         mode: "soft" (default) or "hard" - hard mode also deletes degree-one entity nodes
		 *         user: Authenticated user
		 *
		 *     Returns:
		 *         JSON response indicating success or failure
		 */
		delete: operations["delete_api_delete_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/visualize": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Visualize
		 * @description Generate an HTML visualization of the dataset's knowledge graph.
		 *
		 *     This endpoint creates an interactive HTML visualization of the knowledge graph
		 *     for a specific dataset. The visualization displays nodes and edges representing
		 *     entities and their relationships, allowing users to explore the graph structure
		 *     visually.
		 *
		 *     ## Query Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset to visualize
		 *
		 *     ## Response
		 *     Returns an HTML page containing the interactive graph visualization.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist
		 *     - **403 Forbidden**: User doesn't have permission to read the dataset
		 *     - **500 Internal Server Error**: Error generating visualization
		 *
		 *     ## Notes
		 *     - User must have read permissions on the dataset
		 *     - Visualization is interactive and allows graph exploration
		 */
		get: operations["visualize_api_visualize_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/permissions/datasets/{principal_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Give Datasets Permission To Principal
		 * @description Grant permission on datasets to a principal (user or role).
		 *
		 *     This endpoint allows granting specific permissions on one or more datasets
		 *     to a principal (which can be a user or role). The authenticated user must
		 *     have appropriate permissions to grant access to the specified datasets.
		 *
		 *     ## Path Parameters
		 *     - **principal_id** (UUID): The UUID of the principal (user or role) to grant permission to
		 *
		 *     ## Request Parameters
		 *     - **permission_name** (str): The name of the permission to grant (e.g., "read", "write", "delete")
		 *     - **dataset_ids** (List[UUID]): List of dataset UUIDs to grant permission on
		 *
		 *     ## Response
		 *     Returns a success message indicating permission was assigned.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid request parameters
		 *     - **403 Forbidden**: User doesn't have permission to grant access
		 *     - **500 Internal Server Error**: Error granting permission
		 */
		post: operations["give_datasets_permission_to_principal_api_permissions_datasets__principal_id__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/permissions/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Role
		 * @description Create a new role.
		 *
		 *     This endpoint creates a new role with the specified name. Roles are used
		 *     to group permissions and can be assigned to users to manage access control
		 *     more efficiently. The authenticated user becomes the owner of the created role.
		 *
		 *     ## Request Parameters
		 *     - **role_name** (str): The name of the role to create
		 *
		 *     ## Response
		 *     Returns a success message indicating the role was created.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid role name or role already exists
		 *     - **500 Internal Server Error**: Error creating the role
		 */
		post: operations["create_role_api_permissions_roles_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/permissions/users/{user_id}/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add User To Role
		 * @description Add a user to a role.
		 *
		 *     This endpoint assigns a user to a specific role, granting them all the
		 *     permissions associated with that role. The authenticated user must be
		 *     the owner of the role or have appropriate administrative permissions.
		 *
		 *     ## Path Parameters
		 *     - **user_id** (UUID): The UUID of the user to add to the role
		 *
		 *     ## Request Parameters
		 *     - **role_id** (UUID): The UUID of the role to assign the user to
		 *
		 *     ## Response
		 *     Returns a success message indicating the user was added to the role.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid user or role ID
		 *     - **403 Forbidden**: User doesn't have permission to assign roles
		 *     - **404 Not Found**: User or role doesn't exist
		 *     - **500 Internal Server Error**: Error adding user to role
		 */
		post: operations["add_user_to_role_api_permissions_users__user_id__roles_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/permissions/users/{user_id}/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Add User To Tenant
		 * @description Add a user to a tenant.
		 *
		 *     This endpoint assigns a user to a specific tenant, allowing them to access
		 *     resources and data associated with that tenant. The authenticated user must
		 *     be the owner of the tenant or have appropriate administrative permissions.
		 *
		 *     ## Path Parameters
		 *     - **user_id** (UUID): The UUID of the user to add to the tenant
		 *
		 *     ## Request Parameters
		 *     - **tenant_id** (UUID): The UUID of the tenant to assign the user to
		 *
		 *     ## Response
		 *     Returns a success message indicating the user was added to the tenant.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid user or tenant ID
		 *     - **403 Forbidden**: User doesn't have permission to assign tenants
		 *     - **404 Not Found**: User or tenant doesn't exist
		 *     - **500 Internal Server Error**: Error adding user to tenant
		 */
		post: operations["add_user_to_tenant_api_permissions_users__user_id__tenants_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/permissions/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Tenant
		 * @description Create a new tenant.
		 *
		 *     This endpoint creates a new tenant with the specified name. Tenants are used
		 *     to organize users and resources in multi-tenant environments, providing
		 *     isolation and access control between different groups or organizations.
		 *
		 *     ## Request Parameters
		 *     - **tenant_name** (str): The name of the tenant to create
		 *
		 *     ## Response
		 *     Returns a success message indicating the tenant was created.
		 *
		 *     ## Error Codes
		 *     - **400 Bad Request**: Invalid tenant name or tenant already exists
		 *     - **500 Internal Server Error**: Error creating the tenant
		 */
		post: operations["create_tenant_api_permissions_tenants_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Datasets
		 * @description Get all datasets accessible to the authenticated user.
		 *
		 *     This endpoint retrieves all datasets that the authenticated user has
		 *     read permissions for. The datasets are returned with their metadata
		 *     including ID, name, creation time, and owner information.
		 *
		 *     ## Response
		 *     Returns a list of dataset objects containing:
		 *     - **id**: Unique dataset identifier
		 *     - **name**: Dataset name
		 *     - **created_at**: When the dataset was created
		 *     - **updated_at**: When the dataset was last updated
		 *     - **owner_id**: ID of the dataset owner
		 *
		 *     ## Error Codes
		 *     - **418 I'm a teapot**: Error retrieving datasets
		 */
		get: operations["get_datasets_api_datasets__get"];
		put?: never;
		/**
		 * Create New Dataset
		 * @description Create a new dataset or return existing dataset with the same name.
		 *
		 *     This endpoint creates a new dataset with the specified name. If a dataset
		 *     with the same name already exists for the user, it returns the existing
		 *     dataset instead of creating a duplicate. The user is automatically granted
		 *     all permissions (read, write, share, delete) on the created dataset.
		 *
		 *     ## Request Parameters
		 *     - **dataset_data** (DatasetCreationPayload): Dataset creation parameters containing:
		 *       - **name**: The name for the new dataset
		 *
		 *     ## Response
		 *     Returns the created or existing dataset object containing:
		 *     - **id**: Unique dataset identifier
		 *     - **name**: Dataset name
		 *     - **created_at**: When the dataset was created
		 *     - **updated_at**: When the dataset was last updated
		 *     - **owner_id**: ID of the dataset owner
		 *
		 *     ## Error Codes
		 *     - **418 I'm a teapot**: Error creating dataset
		 */
		post: operations["create_new_dataset_api_datasets__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/{dataset_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Dataset
		 * @description Delete a dataset by its ID.
		 *
		 *     This endpoint permanently deletes a dataset and all its associated data.
		 *     The user must have delete permissions on the dataset to perform this operation.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset to delete
		 *
		 *     ## Response
		 *     No content returned on successful deletion.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist or user doesn't have access
		 *     - **500 Internal Server Error**: Error during deletion
		 */
		delete: operations["delete_dataset_api_datasets__dataset_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/{dataset_id}/data/{data_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete Data
		 * @description Delete a specific data item from a dataset.
		 *
		 *     This endpoint removes a specific data item from a dataset while keeping
		 *     the dataset itself intact. The user must have delete permissions on the
		 *     dataset to perform this operation.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset containing the data
		 *     - **data_id** (UUID): The unique identifier of the data item to delete
		 *
		 *     ## Response
		 *     No content returned on successful deletion.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset or data item doesn't exist, or user doesn't have access
		 *     - **500 Internal Server Error**: Error during deletion
		 */
		delete: operations["delete_data_api_datasets__dataset_id__data__data_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/{dataset_id}/data": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Dataset Data
		 * @description Get all data items in a dataset.
		 *
		 *     This endpoint retrieves all data items (documents, files, etc.) that belong
		 *     to a specific dataset. Each data item includes metadata such as name, type,
		 *     creation time, and storage location.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset
		 *
		 *     ## Response
		 *     Returns a list of data objects containing:
		 *     - **id**: Unique data item identifier
		 *     - **name**: Data item name
		 *     - **created_at**: When the data was added
		 *     - **updated_at**: When the data was last updated
		 *     - **extension**: File extension
		 *     - **mime_type**: MIME type of the data
		 *     - **raw_data_location**: Storage location of the raw data
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset doesn't exist or user doesn't have access
		 *     - **500 Internal Server Error**: Error retrieving data
		 */
		get: operations["get_dataset_data_api_datasets__dataset_id__data_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Dataset Status
		 * @description Get the processing status of datasets.
		 *
		 *     This endpoint retrieves the current processing status of one or more datasets,
		 *     indicating whether they are being processed, have completed processing, or
		 *     encountered errors during pipeline execution.
		 *
		 *     ## Query Parameters
		 *     - **dataset** (List[UUID]): List of dataset UUIDs to check status for
		 *
		 *     ## Response
		 *     Returns a dictionary mapping dataset IDs to their processing status:
		 *     - **pending**: Dataset is queued for processing
		 *     - **running**: Dataset is currently being processed
		 *     - **completed**: Dataset processing completed successfully
		 *     - **failed**: Dataset processing encountered an error
		 *
		 *     ## Error Codes
		 *     - **500 Internal Server Error**: Error retrieving status information
		 */
		get: operations["get_dataset_status_api_datasets_status_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/datasets/{dataset_id}/data/{data_id}/raw": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Raw Data
		 * @description Download the raw data file for a specific data item.
		 *
		 *     This endpoint allows users to download the original, unprocessed data file
		 *     for a specific data item within a dataset. The file is returned as a direct
		 *     download with appropriate headers.
		 *
		 *     ## Path Parameters
		 *     - **dataset_id** (UUID): The unique identifier of the dataset containing the data
		 *     - **data_id** (UUID): The unique identifier of the data item to download
		 *
		 *     ## Response
		 *     Returns the raw data file as a downloadable response.
		 *
		 *     ## Error Codes
		 *     - **404 Not Found**: Dataset or data item doesn't exist, or user doesn't have access
		 *     - **500 Internal Server Error**: Error accessing the raw data file
		 */
		get: operations["get_raw_data_api_datasets__dataset_id__data__data_id__raw_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/notebooks/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Notebooks Endpoint */
		get: operations["get_notebooks_endpoint_api_notebooks__get"];
		put?: never;
		/** Create Notebook Endpoint */
		post: operations["create_notebook_endpoint_api_notebooks__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/notebooks/{notebook_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update Notebook Endpoint */
		put: operations["update_notebook_endpoint_api_notebooks__notebook_id__put"];
		post?: never;
		/** Delete Notebook Endpoint */
		delete: operations["delete_notebook_endpoint_api_notebooks__notebook_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AddPayloadDTO */
		AddPayloadDTO: {
			/**
			 * Textdata
			 * @description Plain-text data
			 * @default [
			 *       "Warning: long-term memory may contain dad jokes!"
			 *     ]
			 */
			textData: string[];
			/** Datasetname */
			datasetName?: string | null;
			/**
			 * Datasetid
			 * @example
			 */
			datasetId?: string | "" | null;
			/** Nodeset */
			nodeSet?: string[] | null;
		};
		/** CognifyPayloadDTO */
		CognifyPayloadDTO: {
			/** Datasets */
			datasets?: string[] | null;
			/**
			 * Datasetids
			 * @example []
			 */
			datasetIds?: string[] | null;
			/**
			 * Runinbackground
			 * @deprecated
			 * @description Disabled on this deployment – must be false if supplied.
			 * @default false
			 */
			runInBackground: false | null;
			/**
			 * Customprompt
			 * @description Custom prompt for entity extraction and graph generation
			 * @default
			 */
			customPrompt: string | null;
			/**
			 * Temporalcognify
			 * @default false
			 */
			temporalCognify: boolean | null;
		};
		/** CombinedSearchResult */
		CombinedSearchResult: {
			/** Result */
			result: unknown | null;
			/** Context */
			context: Record<string, never>;
			/**
			 * Graphs
			 * @default {}
			 */
			graphs: Record<string, never> | null;
			/** Datasets */
			datasets?: components["schemas"]["SearchResultDataset"][] | null;
		};
		/** DataDTO */
		DataDTO: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
			/** Updatedat */
			updatedAt?: string | null;
			/** Extension */
			extension: string;
			/** Mimetype */
			mimeType: string;
			/** Rawdatalocation */
			rawDataLocation: string;
			/**
			 * Datasetid
			 * Format: uuid
			 */
			datasetId: string;
		};
		/** DatasetCreationPayload */
		DatasetCreationPayload: {
			/** Name */
			name: string;
		};
		/** DatasetDTO */
		DatasetDTO: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
			/** Updatedat */
			updatedAt?: string | null;
			/**
			 * Ownerid
			 * Format: uuid
			 */
			ownerId: string;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** NotebookCell */
		NotebookCell: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Type
			 * @enum {string}
			 */
			type: "markdown" | "code";
			/** Name */
			name: string;
			/** Content */
			content: string;
		};
		/** NotebookData */
		NotebookData: {
			/** Name */
			name: string | null;
			/**
			 * Cells
			 * @default []
			 */
			cells: components["schemas"]["NotebookCell"][] | null;
		};
		/**
		 * PipelineRunStatus
		 * @enum {string}
		 */
		PipelineRunStatus:
			| "DATASET_PROCESSING_INITIATED"
			| "DATASET_PROCESSING_STARTED"
			| "DATASET_PROCESSING_COMPLETED"
			| "DATASET_PROCESSING_ERRORED";
		/** SearchHistoryItem */
		SearchHistoryItem: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Text */
			text: string;
			/** User */
			user: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
		};
		/** SearchPayloadDTO */
		SearchPayloadDTO: {
			/** @default GRAPH_COMPLETION */
			searchType: components["schemas"]["SearchType"];
			/** Datasets */
			datasets?: string[] | null;
			/**
			 * Datasetids
			 * @example []
			 */
			datasetIds?: string[] | null;
			/**
			 * Query
			 * @default What is in the document?
			 */
			query: string;
			/**
			 * Systemprompt
			 * @default Answer the question using the provided context. Be as brief as possible.
			 */
			systemPrompt: string | null;
			/**
			 * Nodename
			 * @example []
			 */
			nodeName?: string[] | null;
			/**
			 * Topk
			 * @default 10
			 */
			topK: number | null;
			/**
			 * Onlycontext
			 * @default false
			 */
			onlyContext: boolean;
			/**
			 * Usecombinedcontext
			 * @default false
			 */
			useCombinedContext: boolean;
		};
		/** SearchResult */
		SearchResult: {
			/** Search Result */
			search_result: unknown;
			/** Dataset Id */
			dataset_id: string | null;
			/** Dataset Name */
			dataset_name: string | null;
		};
		/** SearchResultDataset */
		SearchResultDataset: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
		};
		/**
		 * SearchType
		 * @enum {string}
		 */
		SearchType:
			| "SUMMARIES"
			| "INSIGHTS"
			| "CHUNKS"
			| "RAG_COMPLETION"
			| "GRAPH_COMPLETION"
			| "GRAPH_SUMMARY_COMPLETION"
			| "CODE"
			| "CYPHER"
			| "NATURAL_LANGUAGE"
			| "GRAPH_COMPLETION_COT"
			| "GRAPH_COMPLETION_CONTEXT_EXTENSION"
			| "FEELING_LUCKY"
			| "FEEDBACK"
			| "TEMPORAL"
			| "CODING_RULES"
			| "CHUNKS_LEXICAL";
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	add_text_api_add_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AddPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": Record<string, never>;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	cognify_api_cognify_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CognifyPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": Record<string, never>;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_search_history_api_search_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SearchHistoryItem"][];
				};
			};
		};
	};
	search_api_search_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SearchPayloadDTO"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json":
						| components["schemas"]["SearchResult"][]
						| components["schemas"]["CombinedSearchResult"]
						| unknown[];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_api_delete_delete: {
		parameters: {
			query: {
				data_id: string;
				dataset_id: string;
				mode?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	visualize_api_visualize_get: {
		parameters: {
			query: {
				dataset_id: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	give_datasets_permission_to_principal_api_permissions_datasets__principal_id__post: {
		parameters: {
			query: {
				permission_name: string;
			};
			header?: never;
			path: {
				principal_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": string[];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_role_api_permissions_roles_post: {
		parameters: {
			query: {
				role_name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	add_user_to_role_api_permissions_users__user_id__roles_post: {
		parameters: {
			query: {
				role_id: string;
			};
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	add_user_to_tenant_api_permissions_users__user_id__tenants_post: {
		parameters: {
			query: {
				tenant_id: string;
			};
			header?: never;
			path: {
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_tenant_api_permissions_tenants_post: {
		parameters: {
			query: {
				tenant_name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_datasets_api_datasets__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DatasetDTO"][];
				};
			};
		};
	};
	create_new_dataset_api_datasets__post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DatasetCreationPayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DatasetDTO"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_dataset_api_datasets__dataset_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_data_api_datasets__dataset_id__data__data_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
				data_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dataset_data_api_datasets__dataset_id__data_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DataDTO"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dataset_status_api_datasets_status_get: {
		parameters: {
			query?: {
				dataset?: string[];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: components["schemas"]["PipelineRunStatus"];
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_raw_data_api_datasets__dataset_id__data__data_id__raw_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				dataset_id: string;
				data_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_notebooks_endpoint_api_notebooks__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	create_notebook_endpoint_api_notebooks__post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NotebookData"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	update_notebook_endpoint_api_notebooks__notebook_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notebook_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NotebookData"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_notebook_endpoint_api_notebooks__notebook_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notebook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
